model_list:
  - model_name: anthropic/claude-3-haiku-20240307
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      max_tokens: 1000
      temperature: 0.3
      api_key: os.environ/ANTHROPIC_API_KEY
    rpm: 60
    tpm: 200000
  - model_name: anthropic/claude-3-5-sonnet-20240620
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      max_tokens: 1000
      temperature: 0.3
      api_key: os.environ/ANTHROPIC_API_KEY
    rpm: 20
    tpm: 100000
  - model_name: anthropic/claude-3-sonnet-20240229
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      max_tokens: 1000
      temperature: 0.3
      api_key: os.environ/ANTHROPIC_API_KEY
    rpm: 20
    tpm: 100000

general_settings:
  default_model: anthropic/claude-3-haiku-20240307
  logging:
    log_requests: true
    log_file: "/app/logs/requests.json"
    log_cost: true
  budget:
    total_budget: 5
    daily_budget: 1
    user_budget: 0.1
router_settings:
  num_retries: 0