model_list:
  - model_name: anthropic/claude-3-haiku-20240307
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      max_tokens: 1000
      temperature: 0.3
      api_key: os.environ/ANTHROPIC_API_KEY

general_settings:
  default_model: anthropic/claude-3-haiku-20240307
  logging:
    log_requests: true
    log_file: "/app/logs/requests.json"
    log_cost: true
  budget:
    total_budget: 5
    daily_budget: 1
    user_budget: 0.1